model = "grok-4"
model_provider = "xai"

[projects."${USERPROFILE}\\Desktop\\testingcodex"]
trust_level = "trusted"

# Allow file creation and modification
approval_policy = "on-request"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true
